project:
  type: book
  output-dir: ../docs

book:
  chapters:
    - index.qmd
    - nota_editorial.qmd
    - introduccion.qmd
    - hallazgos.qmd
    - conclusiones.qmd
    - fuentes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false
  pdf:
    documentclass: scrreprt

execute:
  echo: false
  warning: false
  message: false