project:
  type: book

book:
  chapters:
    - index.qmd
    - nota_editorial.qmd
    - introduccion.qmd
    - contexto.qmd
    - metodologia.qmd
    - variables.qmd
    - hallazgos.qmd
    - modelos.qmd
    - perfiles.qmd
    - conclusiones.qmd
    - reflexiones.qmd
    - fuentes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: false

execute:
  echo: false
  warning: false
  message: false